### ISSUE TITLE
启动不了咋整

### ISSUE THREAD

**Issue by ddm521** [llllllxy/tiny-url#1]
Error: Invalid or corrupt jarfile /www/wwwroot/srul.cn/src/main/java/org/tinycloud/tinyurl/TinyUrlApplication.java

提示这个

**Comment by llllllxy** [comment]
有具体的截图吗看看，这个需要java17的环境才能运行

**Comment by llllllxy** [comment]
你是用idea打开的吗

**Comment by ddm521** [comment]
![Screenshot_20240403_152257_mark via](https://github.com/llllllxy/tiny-url/assets/125931311/1c667fbf-f68a-41c8-af11-d3801d837385)

**Comment by llllllxy** [comment]
> ![Screenshot_20240403_152257_mark via](https://github.com/llllllxy/tiny-url/assets/125931311/1c667fbf-f68a-41c8-af11-d3801d837385)
> 

你这是咋跑的，在宝塔面板？你没打包吗，得先打包成jar，还得依赖mysql和redis

**Comment by llllllxy** [comment]
需要先改配置文件，然后maven打包成jar包，才能在服务器部署

**Comment by llllllxy** [comment]
你可以先把项目用idea clone下来，在本地先跑了试试

**Comment by ddm521** [comment]
好的谢谢

**Comment by ddm521** [comment]
使用idea，选包mian主类应该选什么

**Comment by llllllxy** [comment]
> 使用idea，选包mian主类应该选什么

 TinyUrlApplication

**Comment by llllllxy** [comment]
直接运行里面的main方法就可以了

**Comment by ddm521** [comment]
![IMG_20240403_215932](https://github.com/llllllxy/tiny-url/assets/125931311/4f257c65-631b-4bcf-88db-af3d4fc2d697)
这咋输入

**Comment by llllllxy** [comment]
> ![IMG_20240403_215932](https://github.com/llllllxy/tiny-url/assets/125931311/4f257c65-631b-4bcf-88db-af3d4fc2d697)
> 这咋输入

？你没有Java基础和spring boot的基础吗

**Comment by llllllxy** [comment]
![image](https://github.com/llllllxy/tiny-url/assets/34022230/6c0feb4a-4bcf-44d7-a57a-1e308e260dc0)
这里不就可以直接运行吗，idea打开项目后，自己就能找到主类

**Comment by llllllxy** [comment]
![image](https://github.com/llllllxy/tiny-url/assets/34022230/045e9f0b-5a3f-4774-9572-a53575b9ab6d)
zhi'jei'zha直接找到这个类，点红框里的那个三角形，也可以直接运行

**Comment by llllllxy** [comment]
你应该用idea打开的是 tiny-url那个文件夹，而不是tiny-url-master

**Comment by llllllxy** [comment]
你得在yml配置文件里，配置上数据库和redis才能启动成功，
![Uploading image.png…]()
成功后，就可以在浏览器里访问了

**Comment by llllllxy** [comment]
![image](https://github.com/llllllxy/tiny-url/assets/34022230/ba8e8c88-973c-4866-858f-43cc464df712)

**Comment by ddm521** [comment]
Error: Could not find or load main class org.tinycloud.tinyurl.TinyUrlApplication
Caused by: java.lang.ClassNotFoundException: org.tinycloud.tinyurl.TinyUrlApplication
这个咋解决呢

**Comment by llllllxy** [comment]
你还是自己先学习一下再搞吧，你这基本上啥也不懂呀

**Comment by ddm521** [comment]
😂这不是来学习了吗

**Comment by llllllxy** [comment]
先学习一下maven这些，依赖得下载下来，编译成功了，才能跑呀

**Comment by llllllxy** [comment]
![image](https://github.com/llllllxy/tiny-url/assets/34022230/d0ad31db-06be-4858-869d-364da1f311f5)
wo'shi'le我试了，本地打包后，是可以成功运行的
`"C:\Program Files\AdoptOpenJDK\jdk-17.0.1+12\bin\java.exe" -jar "D:\IdeaProjects\tiny-url\target\tiny-url-0.0.1-SNAPSHOT.jar"`
